name: SonarCloud Analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List files in workspace
        run: ls -R

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate coverage report
        run: npm test -- --coverage

      - name: List coverage files
        run: ls -R coverage/

      - name: Inspect lcov.info
        run: cat coverage/lcov.info

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=ajhades_gif-expert-app-exe
            -Dsonar.organization=ajhades
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.test.inclusions=**/*.test.js,**/*.test.jsx
            -Dsonar.scm.disabled=true
            -Dsonar.sources=src
            -Dsonar.tests=test
            -Dsonar.analysis.mode=publish
            -Dsonar.language=js
            -Dsonar.verbose=true
          projectBaseDir: .